version: '3.7'

networks:
  docker-world_symfony:

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-symfony
    environment:
      TZ: Europe/Kiev
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - docker-world_symfony

  php:
    build:
      context: ./docker/php
      dockerfile: php-fpm.dockerfile
    container_name: php-symfony
    environment:
      TZ: Europe/Kiev
      DB_HOST: mysqlsymfony
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    ports:
      - "9005:9000"
    networks:
      - docker-world_symfony

#  redis:
#    image: "redis:alpine"
#    ports:
#      - "6380:6379"
#    command: [ "redis-server" ]
#    environment:
#      TZ: Europe/Kiev
#    container_name: redis
#    networks:
#      - docker-world_softsvit