version: '3.8'

networks:
  docker-symfony:
    name: docker-symfony

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-symfony
    environment:
      TZ: Europe/Kiev
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker-symfony

  php:
    build:
      context: ./docker/php
      dockerfile: php-fpm.dockerfile
    container_name: php-symfony
    environment:
      TZ: Europe/Kiev
      DB_HOST: mysql-symfony
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    ports:
      - "9005:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker-symfony

  redis:
    image: "redis:alpine"
    container_name: redis-symfony
    ports:
      - "6380:6379"
    command: [ "redis-server" ]
    environment:
      TZ: Europe/Kiev
    networks:
      - docker-symfony

  mysql:
    image: mysql:8.0
    container_name: mysql-symfony
    restart: always
    environment:
      TZ: Europe/Kiev
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - docker-symfony